package com.stanks.andsokoban_full.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_s_main_pnl{

public static void LS_480x320_1(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("panel1").vw.setLeft((int)(0d));
views.get("panel1").vw.setTop((int)(0d));
views.get("panel1").vw.setWidth((int)((100d / 100 * width)));
views.get("label1").vw.setLeft((int)(0d));
views.get("label1").vw.setTop((int)(0d));
views.get("label1").vw.setWidth((int)((100d / 100 * width)));
views.get("label1").vw.setHeight((int)((10d / 100 * width)));
views.get("button1").vw.setLeft((int)((6d / 100 * width)));
views.get("button1").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button1").vw.setWidth((int)((12d / 100 * width)));
views.get("button1").vw.setHeight((int)((12d / 100 * width)));
views.get("button2").vw.setLeft((int)((views.get("button1").vw.getLeft() + views.get("button1").vw.getWidth())+(3d / 100 * width)));
views.get("button2").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button2").vw.setWidth((int)((12d / 100 * width)));
views.get("button2").vw.setHeight((int)((12d / 100 * width)));
views.get("button3").vw.setLeft((int)((views.get("button2").vw.getLeft() + views.get("button2").vw.getWidth())+(3d / 100 * width)));
views.get("button3").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button3").vw.setWidth((int)((12d / 100 * width)));
views.get("button3").vw.setHeight((int)((12d / 100 * width)));
views.get("button4").vw.setLeft((int)((views.get("button3").vw.getLeft() + views.get("button3").vw.getWidth())+(3d / 100 * width)));
views.get("button4").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button4").vw.setWidth((int)((12d / 100 * width)));
views.get("button4").vw.setHeight((int)((12d / 100 * width)));
views.get("button5").vw.setLeft((int)((views.get("button4").vw.getLeft() + views.get("button4").vw.getWidth())+(3d / 100 * width)));
views.get("button5").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button5").vw.setWidth((int)((12d / 100 * width)));
views.get("button5").vw.setHeight((int)((12d / 100 * width)));
views.get("button6").vw.setLeft((int)((views.get("button5").vw.getLeft() + views.get("button5").vw.getWidth())+(3d / 100 * width)));
views.get("button6").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button6").vw.setWidth((int)((12d / 100 * width)));
views.get("button6").vw.setHeight((int)((12d / 100 * width)));
views.get("button7").vw.setLeft((int)((6d / 100 * width)));
views.get("button7").vw.setTop((int)((views.get("button1").vw.getTop() + views.get("button1").vw.getHeight())+(3d / 100 * height)));
views.get("button7").vw.setWidth((int)((12d / 100 * width)));
views.get("button7").vw.setHeight((int)((12d / 100 * width)));
views.get("button8").vw.setLeft((int)((views.get("button7").vw.getLeft() + views.get("button7").vw.getWidth())+(3d / 100 * width)));
views.get("button8").vw.setTop((int)((views.get("button2").vw.getTop() + views.get("button2").vw.getHeight())+(3d / 100 * height)));
views.get("button8").vw.setWidth((int)((12d / 100 * width)));
views.get("button8").vw.setHeight((int)((12d / 100 * width)));
views.get("button9").vw.setLeft((int)((views.get("button8").vw.getLeft() + views.get("button8").vw.getWidth())+(3d / 100 * width)));
views.get("button9").vw.setTop((int)((views.get("button3").vw.getTop() + views.get("button3").vw.getHeight())+(3d / 100 * height)));
views.get("button9").vw.setWidth((int)((12d / 100 * width)));
views.get("button9").vw.setHeight((int)((12d / 100 * width)));
views.get("button10").vw.setLeft((int)((views.get("button9").vw.getLeft() + views.get("button9").vw.getWidth())+(3d / 100 * width)));
views.get("button10").vw.setTop((int)((views.get("button4").vw.getTop() + views.get("button4").vw.getHeight())+(3d / 100 * height)));
views.get("button10").vw.setWidth((int)((12d / 100 * width)));
views.get("button10").vw.setHeight((int)((12d / 100 * width)));
views.get("button11").vw.setLeft((int)((views.get("button10").vw.getLeft() + views.get("button10").vw.getWidth())+(3d / 100 * width)));
views.get("button11").vw.setTop((int)((views.get("button5").vw.getTop() + views.get("button5").vw.getHeight())+(3d / 100 * height)));
views.get("button11").vw.setWidth((int)((12d / 100 * width)));
views.get("button11").vw.setHeight((int)((12d / 100 * width)));
views.get("button12").vw.setLeft((int)((views.get("button11").vw.getLeft() + views.get("button11").vw.getWidth())+(3d / 100 * width)));
views.get("button12").vw.setTop((int)((views.get("button6").vw.getTop() + views.get("button6").vw.getHeight())+(3d / 100 * height)));
views.get("button12").vw.setWidth((int)((12d / 100 * width)));
views.get("button12").vw.setHeight((int)((12d / 100 * width)));
views.get("button13").vw.setLeft((int)((6d / 100 * width)));
views.get("button13").vw.setTop((int)((views.get("button7").vw.getTop() + views.get("button7").vw.getHeight())+(3d / 100 * height)));
views.get("button13").vw.setWidth((int)((12d / 100 * width)));
views.get("button13").vw.setHeight((int)((12d / 100 * width)));
views.get("button14").vw.setLeft((int)((views.get("button13").vw.getLeft() + views.get("button13").vw.getWidth())+(3d / 100 * width)));
views.get("button14").vw.setTop((int)((views.get("button8").vw.getTop() + views.get("button8").vw.getHeight())+(3d / 100 * height)));
views.get("button14").vw.setWidth((int)((12d / 100 * width)));
views.get("button14").vw.setHeight((int)((12d / 100 * width)));
views.get("button15").vw.setLeft((int)((views.get("button14").vw.getLeft() + views.get("button14").vw.getWidth())+(3d / 100 * width)));
views.get("button15").vw.setTop((int)((views.get("button9").vw.getTop() + views.get("button9").vw.getHeight())+(3d / 100 * height)));
views.get("button15").vw.setWidth((int)((12d / 100 * width)));
views.get("button15").vw.setHeight((int)((12d / 100 * width)));
views.get("button16").vw.setLeft((int)((views.get("button15").vw.getLeft() + views.get("button15").vw.getWidth())+(3d / 100 * width)));
views.get("button16").vw.setTop((int)((views.get("button10").vw.getTop() + views.get("button10").vw.getHeight())+(3d / 100 * height)));
views.get("button16").vw.setWidth((int)((12d / 100 * width)));
views.get("button16").vw.setHeight((int)((12d / 100 * width)));
views.get("button17").vw.setLeft((int)((views.get("button16").vw.getLeft() + views.get("button16").vw.getWidth())+(3d / 100 * width)));
views.get("button17").vw.setTop((int)((views.get("button11").vw.getTop() + views.get("button11").vw.getHeight())+(3d / 100 * height)));
views.get("button17").vw.setWidth((int)((12d / 100 * width)));
views.get("button17").vw.setHeight((int)((12d / 100 * width)));
views.get("button18").vw.setLeft((int)((views.get("button17").vw.getLeft() + views.get("button17").vw.getWidth())+(3d / 100 * width)));
views.get("button18").vw.setTop((int)((views.get("button12").vw.getTop() + views.get("button12").vw.getHeight())+(3d / 100 * height)));
views.get("button18").vw.setWidth((int)((12d / 100 * width)));
views.get("button18").vw.setHeight((int)((12d / 100 * width)));
views.get("button19").vw.setLeft((int)((6d / 100 * width)));
views.get("button19").vw.setTop((int)((views.get("button13").vw.getTop() + views.get("button13").vw.getHeight())+(3d / 100 * height)));
views.get("button19").vw.setWidth((int)((12d / 100 * width)));
views.get("button19").vw.setHeight((int)((12d / 100 * width)));
views.get("button20").vw.setLeft((int)((views.get("button19").vw.getLeft() + views.get("button19").vw.getWidth())+(3d / 100 * width)));
views.get("button20").vw.setTop((int)((views.get("button14").vw.getTop() + views.get("button14").vw.getHeight())+(3d / 100 * height)));
views.get("button20").vw.setWidth((int)((12d / 100 * width)));
views.get("button20").vw.setHeight((int)((12d / 100 * width)));
views.get("button21").vw.setLeft((int)((views.get("button20").vw.getLeft() + views.get("button20").vw.getWidth())+(3d / 100 * width)));
views.get("button21").vw.setTop((int)((views.get("button15").vw.getTop() + views.get("button15").vw.getHeight())+(3d / 100 * height)));
views.get("button21").vw.setWidth((int)((12d / 100 * width)));
views.get("button21").vw.setHeight((int)((12d / 100 * width)));
views.get("button22").vw.setLeft((int)((views.get("button21").vw.getLeft() + views.get("button21").vw.getWidth())+(3d / 100 * width)));
views.get("button22").vw.setTop((int)((views.get("button16").vw.getTop() + views.get("button16").vw.getHeight())+(3d / 100 * height)));
views.get("button22").vw.setWidth((int)((12d / 100 * width)));
views.get("button22").vw.setHeight((int)((12d / 100 * width)));
views.get("button23").vw.setLeft((int)((views.get("button22").vw.getLeft() + views.get("button22").vw.getWidth())+(3d / 100 * width)));
views.get("button23").vw.setTop((int)((views.get("button17").vw.getTop() + views.get("button17").vw.getHeight())+(3d / 100 * height)));
views.get("button23").vw.setWidth((int)((12d / 100 * width)));
views.get("button23").vw.setHeight((int)((12d / 100 * width)));
views.get("button24").vw.setLeft((int)((views.get("button23").vw.getLeft() + views.get("button23").vw.getWidth())+(3d / 100 * width)));
views.get("button24").vw.setTop((int)((views.get("button18").vw.getTop() + views.get("button18").vw.getHeight())+(3d / 100 * height)));
views.get("button24").vw.setWidth((int)((12d / 100 * width)));
views.get("button24").vw.setHeight((int)((12d / 100 * width)));
views.get("button25").vw.setLeft((int)((views.get("button20").vw.getLeft() + views.get("button20").vw.getWidth())-(4d / 100 * width)));
views.get("button25").vw.setTop((int)((views.get("button19").vw.getTop() + views.get("button19").vw.getHeight())+(3d / 100 * height)));
views.get("button25").vw.setWidth((int)((12d / 100 * width)));
views.get("button25").vw.setHeight((int)((12d / 100 * width)));
views.get("button27").vw.setLeft((int)((views.get("button25").vw.getLeft() + views.get("button25").vw.getWidth())+(3d / 100 * width)));
views.get("button27").vw.setTop((int)((views.get("button22").vw.getTop() + views.get("button22").vw.getHeight())+(3d / 100 * height)));
views.get("button27").vw.setWidth((int)((12d / 100 * width)));
views.get("button27").vw.setHeight((int)((12d / 100 * width)));
views.get("button26").vw.setLeft((int)((views.get("button27").vw.getLeft() + views.get("button27").vw.getWidth())+(3d / 100 * width)));
views.get("button26").vw.setTop((int)((views.get("button23").vw.getTop() + views.get("button23").vw.getHeight())+(3d / 100 * height)));
views.get("button26").vw.setWidth((int)((12d / 100 * width)));
views.get("button26").vw.setHeight((int)((12d / 100 * width)));
views.get("btnopcije").vw.setLeft((int)((5d / 100 * width)));
views.get("btnopcije").vw.setTop((int)((views.get("button27").vw.getTop() + views.get("button27").vw.getHeight())+(3d / 100 * height)));
views.get("btnopcije").vw.setWidth((int)((15d / 100 * width)));
views.get("btnopcije").vw.setHeight((int)((15d / 100 * width)));
views.get("btno").vw.setLeft((int)((100d / 100 * width)-(20d / 100 * width)));
views.get("btno").vw.setTop((int)((views.get("button26").vw.getTop() + views.get("button26").vw.getHeight())+(3d / 100 * height)));
views.get("btno").vw.setWidth((int)((15d / 100 * width)));
views.get("btno").vw.setHeight((int)((15d / 100 * width)));
views.get("panel1").vw.setHeight((int)((views.get("button1").vw.getHeight())+(3d / 100 * height)+(views.get("button6").vw.getHeight())+(3d / 100 * height)+(views.get("button11").vw.getHeight())+(3d / 100 * height)+(views.get("button16").vw.getHeight())+(3d / 100 * height)+(views.get("button21").vw.getHeight())+(3d / 100 * height)+(views.get("button27").vw.getHeight())+(3d / 100 * height)+(views.get("btnopcije").vw.getHeight())+(1d / 100 * height)));

}
public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("panel1").vw.setLeft((int)(0d));
views.get("panel1").vw.setTop((int)(0d));
views.get("panel1").vw.setWidth((int)((100d / 100 * width)));
views.get("label1").vw.setLeft((int)(0d));
views.get("label1").vw.setTop((int)(0d));
views.get("label1").vw.setWidth((int)((100d / 100 * width)));
views.get("label1").vw.setHeight((int)((10d / 100 * width)));
views.get("button1").vw.setLeft((int)((6d / 100 * width)));
views.get("button1").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button1").vw.setWidth((int)((12d / 100 * width)));
views.get("button1").vw.setHeight((int)((12d / 100 * width)));
views.get("button2").vw.setLeft((int)((views.get("button1").vw.getLeft() + views.get("button1").vw.getWidth())+(3d / 100 * width)));
views.get("button2").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button2").vw.setWidth((int)((12d / 100 * width)));
views.get("button2").vw.setHeight((int)((12d / 100 * width)));
views.get("button3").vw.setLeft((int)((views.get("button2").vw.getLeft() + views.get("button2").vw.getWidth())+(3d / 100 * width)));
views.get("button3").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button3").vw.setWidth((int)((12d / 100 * width)));
views.get("button3").vw.setHeight((int)((12d / 100 * width)));
views.get("button4").vw.setLeft((int)((views.get("button3").vw.getLeft() + views.get("button3").vw.getWidth())+(3d / 100 * width)));
views.get("button4").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button4").vw.setWidth((int)((12d / 100 * width)));
views.get("button4").vw.setHeight((int)((12d / 100 * width)));
views.get("button5").vw.setLeft((int)((views.get("button4").vw.getLeft() + views.get("button4").vw.getWidth())+(3d / 100 * width)));
views.get("button5").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button5").vw.setWidth((int)((12d / 100 * width)));
views.get("button5").vw.setHeight((int)((12d / 100 * width)));
views.get("button6").vw.setLeft((int)((views.get("button5").vw.getLeft() + views.get("button5").vw.getWidth())+(3d / 100 * width)));
views.get("button6").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("button6").vw.setWidth((int)((12d / 100 * width)));
views.get("button6").vw.setHeight((int)((12d / 100 * width)));
views.get("button7").vw.setLeft((int)((6d / 100 * width)));
views.get("button7").vw.setTop((int)((views.get("button1").vw.getTop() + views.get("button1").vw.getHeight())+(3d / 100 * height)));
views.get("button7").vw.setWidth((int)((12d / 100 * width)));
views.get("button7").vw.setHeight((int)((12d / 100 * width)));
views.get("button8").vw.setLeft((int)((views.get("button7").vw.getLeft() + views.get("button7").vw.getWidth())+(3d / 100 * width)));
views.get("button8").vw.setTop((int)((views.get("button2").vw.getTop() + views.get("button2").vw.getHeight())+(3d / 100 * height)));
views.get("button8").vw.setWidth((int)((12d / 100 * width)));
views.get("button8").vw.setHeight((int)((12d / 100 * width)));
views.get("button9").vw.setLeft((int)((views.get("button8").vw.getLeft() + views.get("button8").vw.getWidth())+(3d / 100 * width)));
views.get("button9").vw.setTop((int)((views.get("button3").vw.getTop() + views.get("button3").vw.getHeight())+(3d / 100 * height)));
views.get("button9").vw.setWidth((int)((12d / 100 * width)));
views.get("button9").vw.setHeight((int)((12d / 100 * width)));
views.get("button10").vw.setLeft((int)((views.get("button9").vw.getLeft() + views.get("button9").vw.getWidth())+(3d / 100 * width)));
views.get("button10").vw.setTop((int)((views.get("button4").vw.getTop() + views.get("button4").vw.getHeight())+(3d / 100 * height)));
views.get("button10").vw.setWidth((int)((12d / 100 * width)));
views.get("button10").vw.setHeight((int)((12d / 100 * width)));
views.get("button11").vw.setLeft((int)((views.get("button10").vw.getLeft() + views.get("button10").vw.getWidth())+(3d / 100 * width)));
views.get("button11").vw.setTop((int)((views.get("button5").vw.getTop() + views.get("button5").vw.getHeight())+(3d / 100 * height)));
views.get("button11").vw.setWidth((int)((12d / 100 * width)));
views.get("button11").vw.setHeight((int)((12d / 100 * width)));
views.get("button12").vw.setLeft((int)((views.get("button11").vw.getLeft() + views.get("button11").vw.getWidth())+(3d / 100 * width)));
views.get("button12").vw.setTop((int)((views.get("button6").vw.getTop() + views.get("button6").vw.getHeight())+(3d / 100 * height)));
views.get("button12").vw.setWidth((int)((12d / 100 * width)));
views.get("button12").vw.setHeight((int)((12d / 100 * width)));
views.get("button13").vw.setLeft((int)((6d / 100 * width)));
views.get("button13").vw.setTop((int)((views.get("button7").vw.getTop() + views.get("button7").vw.getHeight())+(3d / 100 * height)));
views.get("button13").vw.setWidth((int)((12d / 100 * width)));
views.get("button13").vw.setHeight((int)((12d / 100 * width)));
views.get("button14").vw.setLeft((int)((views.get("button13").vw.getLeft() + views.get("button13").vw.getWidth())+(3d / 100 * width)));
views.get("button14").vw.setTop((int)((views.get("button8").vw.getTop() + views.get("button8").vw.getHeight())+(3d / 100 * height)));
views.get("button14").vw.setWidth((int)((12d / 100 * width)));
views.get("button14").vw.setHeight((int)((12d / 100 * width)));
views.get("button15").vw.setLeft((int)((views.get("button14").vw.getLeft() + views.get("button14").vw.getWidth())+(3d / 100 * width)));
views.get("button15").vw.setTop((int)((views.get("button9").vw.getTop() + views.get("button9").vw.getHeight())+(3d / 100 * height)));
views.get("button15").vw.setWidth((int)((12d / 100 * width)));
views.get("button15").vw.setHeight((int)((12d / 100 * width)));
views.get("button16").vw.setLeft((int)((views.get("button15").vw.getLeft() + views.get("button15").vw.getWidth())+(3d / 100 * width)));
views.get("button16").vw.setTop((int)((views.get("button10").vw.getTop() + views.get("button10").vw.getHeight())+(3d / 100 * height)));
views.get("button16").vw.setWidth((int)((12d / 100 * width)));
views.get("button16").vw.setHeight((int)((12d / 100 * width)));
views.get("button17").vw.setLeft((int)((views.get("button16").vw.getLeft() + views.get("button16").vw.getWidth())+(3d / 100 * width)));
views.get("button17").vw.setTop((int)((views.get("button11").vw.getTop() + views.get("button11").vw.getHeight())+(3d / 100 * height)));
views.get("button17").vw.setWidth((int)((12d / 100 * width)));
views.get("button17").vw.setHeight((int)((12d / 100 * width)));
views.get("button18").vw.setLeft((int)((views.get("button17").vw.getLeft() + views.get("button17").vw.getWidth())+(3d / 100 * width)));
views.get("button18").vw.setTop((int)((views.get("button12").vw.getTop() + views.get("button12").vw.getHeight())+(3d / 100 * height)));
views.get("button18").vw.setWidth((int)((12d / 100 * width)));
views.get("button18").vw.setHeight((int)((12d / 100 * width)));
views.get("button19").vw.setLeft((int)((6d / 100 * width)));
views.get("button19").vw.setTop((int)((views.get("button13").vw.getTop() + views.get("button13").vw.getHeight())+(3d / 100 * height)));
views.get("button19").vw.setWidth((int)((12d / 100 * width)));
views.get("button19").vw.setHeight((int)((12d / 100 * width)));
views.get("button20").vw.setLeft((int)((views.get("button19").vw.getLeft() + views.get("button19").vw.getWidth())+(3d / 100 * width)));
views.get("button20").vw.setTop((int)((views.get("button14").vw.getTop() + views.get("button14").vw.getHeight())+(3d / 100 * height)));
views.get("button20").vw.setWidth((int)((12d / 100 * width)));
views.get("button20").vw.setHeight((int)((12d / 100 * width)));
views.get("button21").vw.setLeft((int)((views.get("button20").vw.getLeft() + views.get("button20").vw.getWidth())+(3d / 100 * width)));
views.get("button21").vw.setTop((int)((views.get("button15").vw.getTop() + views.get("button15").vw.getHeight())+(3d / 100 * height)));
views.get("button21").vw.setWidth((int)((12d / 100 * width)));
views.get("button21").vw.setHeight((int)((12d / 100 * width)));
views.get("button22").vw.setLeft((int)((views.get("button21").vw.getLeft() + views.get("button21").vw.getWidth())+(3d / 100 * width)));
views.get("button22").vw.setTop((int)((views.get("button16").vw.getTop() + views.get("button16").vw.getHeight())+(3d / 100 * height)));
views.get("button22").vw.setWidth((int)((12d / 100 * width)));
views.get("button22").vw.setHeight((int)((12d / 100 * width)));
views.get("button23").vw.setLeft((int)((views.get("button22").vw.getLeft() + views.get("button22").vw.getWidth())+(3d / 100 * width)));
views.get("button23").vw.setTop((int)((views.get("button17").vw.getTop() + views.get("button17").vw.getHeight())+(3d / 100 * height)));
views.get("button23").vw.setWidth((int)((12d / 100 * width)));
views.get("button23").vw.setHeight((int)((12d / 100 * width)));
views.get("button24").vw.setLeft((int)((views.get("button23").vw.getLeft() + views.get("button23").vw.getWidth())+(3d / 100 * width)));
views.get("button24").vw.setTop((int)((views.get("button18").vw.getTop() + views.get("button18").vw.getHeight())+(3d / 100 * height)));
views.get("button24").vw.setWidth((int)((12d / 100 * width)));
views.get("button24").vw.setHeight((int)((12d / 100 * width)));
views.get("button25").vw.setLeft((int)((views.get("button20").vw.getLeft() + views.get("button20").vw.getWidth())-(4d / 100 * width)));
views.get("button25").vw.setTop((int)((views.get("button19").vw.getTop() + views.get("button19").vw.getHeight())+(3d / 100 * height)));
views.get("button25").vw.setWidth((int)((12d / 100 * width)));
views.get("button25").vw.setHeight((int)((12d / 100 * width)));
views.get("button27").vw.setLeft((int)((views.get("button25").vw.getLeft() + views.get("button25").vw.getWidth())+(3d / 100 * width)));
views.get("button27").vw.setTop((int)((views.get("button22").vw.getTop() + views.get("button22").vw.getHeight())+(3d / 100 * height)));
views.get("button27").vw.setWidth((int)((12d / 100 * width)));
views.get("button27").vw.setHeight((int)((12d / 100 * width)));
views.get("button26").vw.setLeft((int)((views.get("button27").vw.getLeft() + views.get("button27").vw.getWidth())+(3d / 100 * width)));
views.get("button26").vw.setTop((int)((views.get("button23").vw.getTop() + views.get("button23").vw.getHeight())+(3d / 100 * height)));
views.get("button26").vw.setWidth((int)((12d / 100 * width)));
views.get("button26").vw.setHeight((int)((12d / 100 * width)));
views.get("btnopcije").vw.setLeft((int)((5d / 100 * width)));
views.get("btnopcije").vw.setTop((int)((views.get("button27").vw.getTop() + views.get("button27").vw.getHeight())+(3d / 100 * height)));
views.get("btnopcije").vw.setWidth((int)((15d / 100 * width)));
views.get("btnopcije").vw.setHeight((int)((15d / 100 * width)));
views.get("btno").vw.setLeft((int)((100d / 100 * width)-(20d / 100 * width)));
views.get("btno").vw.setTop((int)((views.get("button26").vw.getTop() + views.get("button26").vw.getHeight())+(3d / 100 * height)));
views.get("btno").vw.setWidth((int)((15d / 100 * width)));
views.get("btno").vw.setHeight((int)((15d / 100 * width)));
views.get("panel1").vw.setHeight((int)((views.get("button1").vw.getHeight())+(3d / 100 * height)+(views.get("button6").vw.getHeight())+(3d / 100 * height)+(views.get("button11").vw.getHeight())+(3d / 100 * height)+(views.get("button16").vw.getHeight())+(3d / 100 * height)+(views.get("button21").vw.getHeight())+(3d / 100 * height)+(views.get("button27").vw.getHeight())+(3d / 100 * height)+(views.get("btnopcije").vw.getHeight())+(1d / 100 * height)));

}
}